# Sample Configuration

sampleList:

  ##########################
  # ND FHC
  ##########################

  - name: "ND FHC #nu_{#mu}_like CC "
    isEnabled: true
    binning: "./inputs/samples/binning_DUNE/ND_dune_binning_recoE_numu.txt"
    selectionCutStr: "isFD == 0 && isCC == 1 && numu_CC"
    dataSets: [ "ND" ]


  - name: "ND FHC #nu_{e}_like CC "
    isEnabled: true
    binning: "./inputs/samples/binning_DUNE/ND_dune_binning_recoE_nue.txt"
    selectionCutStr: "isFD == 0 && isCC == 1 && nue_CC"
    dataSets: [ "ND" ]

  ##########################
  # FD FHC
  ##########################

  - name: "FD FHC #nu_{#mu}_like CC "
    isEnabled: true
    binning: "./inputs/samples/binning_DUNE/ND_dune_binning_recoE_numu.txt"
    selectionCuts: "(isCC==1||isNC==1) && LBL == 1 && numu_CC && detNuFlavor==14 && isFD == 1" # for osc case
    dataSets: [ "FD" ]

  - name: "FD FHC #nu_{e}_like CC "
    isEnabled: true
    binning: "./inputs/samples/binning_DUNE/ND_dune_binning_recoE_nue.txt"
    selectionCuts: "(isCC==1||isNC==1) && LBL == 1 && nue_CC && detNuFlavor==12 && isFD == 1" 
    dataSets: [ "FD" ]

  ##########################
  # FD RHC
  ##########################

  - name: "FD RHC #nu_{#mu}_like CC "
    isEnabled: true
    binning: "./inputs/samples/binning_DUNE/ND_dune_binning_recoE_numu.txt"
    selectionCuts: "(isCC==1||isNC==1) && LBL == 1 && anumu_CC && detNuFlavor==14 && isFD == 1" 
    dataSets: [ "FD" ]

  - name: "FD RHC #nu_{e}_like CC "
    isEnabled: true
    binning: "./inputs/samples/binning_DUNE/ND_dune_binning_recoE_nue.txt"
    selectionCuts: "(isCC==1||isNC==1) && LBL == 1 && anue_CC && detNuFlavor==12 && isFD == 1"  
    dataSets: [ "FD" ]
