#!/bin/bash

TABULATE_SOURCE=${PWD}

TABULATE_BUILD_DIR="${PWD}/build-$(uname -m)"

TABULATE_DEFINES=""
TABULATE_DEFINES+=" -DUseGPU=1 "
TABULATE_DEFINES+=" -DUseMultithreading=1 "
TABULATE_DEFINES+=" -DUseDoubles=1 "
TABULATE_DEFINES+=" -DUseCUDAProb3=1 "
TABULATE_DEFINES+=" -DUseCUDAProb3Linear=0 "
TABULATE_DEFINES+=" -DUseOscProb=1 "
TABULATE_DEFINES+=" -DUseProb3ppLinear=0 "
TABULATE_DEFINES+=" -DUseNuFASTLinear=1 "
TABULATE_DEFINES+=" -DUseProbGPULinear=1 "

if [ ! -d ${TABULATE_BUILD_DIR} ]; then
    mkdir ${TABULATE_BUILD_DIR}
fi

cd ${TABULATE_BUILD_DIR}
cmake -DCMAKE_INSTALL_PREFIX=${PWD} ${TABULATE_DEFINES} ${TABULATE_SOURCE} -DCMAKE_CUDA_ARCHITECTURES="all"
make install
